name = "sg-analytics-engine"
main = "src/index.ts"
compatibility_date = "2025-09-23"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = false

[vars]
MAX_ITERATIONS = "10"

[[durable_objects.bindings]]
name = "ORCHESTRATOR"
class_name = "AnalysisOrchestrator"

[[migrations]]
tag = "v1"
new_classes = ["AnalysisOrchestrator"]

[[kv_namespaces]]
binding = "KV"
id = "5884f641df3441deb36344e8be2e5ab6"
