const fs = require('fs');
const lines = [
"import { secp256k1 } from '@noble/curves/secp256k1';",
"import { sha256 } from '@noble/hashes/sha256';",
"import { bytesToHex, hexToBytes } from '@noble/curves/abstract/utils';",
"",
"export interface IterationResult {",
"  python: string;",
"  summary: string;",
"  enough: boolean;",
"  reason: string;",
"}",
"",
"const GONKA_NODES = [",
"  'http://node1.gonka.ai:8000',",
"  'http://node2.gonka.ai:8000',",
"  'http://node3.gonka.ai:8000',",
"];",
"",
"function hexToUint8(hex: string): Uint8Array {",
"  const h = hex.startsWith('0x') ? hex.slice(2) : hex;",
"  return hexToBytes(h);",
"}",
"",
"function getAddress(privateKeyHex: string): string {",
"  const privKey = hexToUint8(privateKeyHex);",
"  const pubKey = secp256k1.getPublicKey(privKey, true);",
"  const hash = sha256(pubKey);",
"  return 'gonka1' + bytesToHex(hash).slice(0, 38);",
"}",
"",
"async function gonkaFetch(url: string, body: string, privateKeyHex: string, transferAddress: string): Promise<Response> {",
"  const timestamp = (Date.now() * 1000000).toString();",
"  const encoder = new TextEncoder();",
"  const payload = encoder.encode(body + timestamp + transferAddress);",
"  const msgHash = sha256(payload);",
"  const privKey = hexToUint8(privateKeyHex);",
"  const sig = secp256k1.sign(msgHash, privKey);",
"  const sigHex = bytesToHex(sig.toCompactRawBytes());",
"  const sigB64 = btoa(String.fromCharCode(...hexToUint8(sigHex)));",
"  const address = getAddress(privateKeyHex);",
"  return fetch(url, {",
"    method: 'POST',",
"    headers: {",
"      'Content-Type': 'application/json',",
"      'Authorization': sigB64,",
"      'X-Timestamp': timestamp,",
"      'X-Requester-Address': address,",
"    },",
"    body,",
"  });",
"}",
"",
"async function getParticipants(): Promise<{url: string, address: string}[]> {",
"  const node = GONKA_NODES[Math.floor(Math.random() * GONKA_NODES.length)];",
"  const resp = await fetch(node + '/v1/epochs/current/participants');",
"  if (!resp.ok) throw new Error('Failed to get participants');",
"  const data: any = await resp.json();",
"  const participants = Array.isArray(data) ? data : (data.participants || []);",
"  return participants",
"    .filter((p: any) => p.inference_url && p.index)",
"    .slice(0, 10)",
"    .map((p: any) => ({ url: p.inference_url + '/v1/chat/completions', address: p.index }));",
"}",
"",
"export class KimiClient {",
"  private privateKey: string;",
"  private model: string;",
"",
"  constructor(privateKey: string) {",
"    this.privateKey = privateKey;",
"    this.model = 'moonshotai/Kimi-K2.6';",
"  }",
"",
"  async generateIteration(dataDescription: string, question: string, iterationSummaries: string[], iteration: number, maxIterations: number): Promise<IterationResult> {",
"    const systemPrompt = 'You are a Python data analyst. Each iteration: write focused Python under 25 lines for ONE hypothesis, summarize in 30 words, signal enough=true when done. FORBIDDEN: pandas/numpy/matplotlib. CSV in CSV_DATA. Output: print(json.dumps({\"result\":...})). Return JSON only: {\"python\":\"...\",\"summary\":\"...\",\"enough\":bool,\"reason\":\"...\"}';",
"    const contextBlock = iterationSummaries.length > 0 ? '\\n\\nKnown: ' + iterationSummaries.map((s,i) => (i+1)+': '+s).join('; ') : '';",
"    const userMessage = 'Schema:\\n' + dataDescription + '\\n\\nQuestion: ' + question + ' (iter ' + iteration + '/' + maxIterations + ')' + contextBlock + '\\n\\nOne hypothesis, no repeats.';",
"    console.log('[KIMI:PROMPT] iter=' + iteration + ' summaries=' + iterationSummaries.length);",
"    const t0 = Date.now();",
"    const raw = await this.callAPI(systemPrompt, userMessage, 2000, 'iter'+iteration);",
"    console.log('[KIMI:DONE] iter=' + iteration + ' elapsed=' + (Date.now()-t0) + 'ms');",
"    return this.parseIterationResult(raw, iteration);",
"  }",
"",
"  async generateFinalAnalysis(question: string, summaries: string[], language: string = 'ru'): Promise<string> {",
"    const lang = language === 'ru' ? 'Respond in Russian. Plain text, no markdown.' : 'Respond in English.';",
"    const sys = 'You are a business analyst. ' + lang + ' Give: 1-2 sentence summary, key findings, 1 recommendation.';",
"    const msg = 'Question: ' + question + '\\n\\nFindings:\\n' + summaries.map((s,i) => (i+1)+'. '+s).join('\\n');",
"    return await this.callAPI(sys, msg, 1000, 'final');",
"  }",
"",
"  private async callAPI(systemPrompt: string, userMessage: string, maxTokens: number, label: string): Promise<string> {",
"    try {",
"      const participants = await getParticipants();",
"      if (participants.length === 0) throw new Error('No participants found');",
"      const endpoint = participants[Math.floor(Math.random() * participants.length)];",
"      const body = JSON.stringify({",
"        model: this.model,",
"        max_tokens: maxTokens,",
"        messages: [{role:'system',content:systemPrompt},{role:'user',content:userMessage}],",
"        temperature: 0.6,",
"      });",
"      const resp = await gonkaFetch(endpoint.url, body, this.privateKey, endpoint.address);",
"      if (!resp.ok) {",
"        const err = await resp.text();",
"        throw new Error('Gonka API error ' + resp.status + ': ' + err.slice(0, 200));",
"      }",
"      const data: any = await resp.json();",
"      const content = data.choices?.[0]?.message?.content || '';",
"      console.log('[KIMI:API] label=' + label + ' tokens=' + data.usage?.total_tokens);",
"      return content.trim();",
"    } catch(err) {",
"      console.error('[KIMI:ERROR] label=' + label + ' error=' + String(err));",
"      throw err;",
"    }",
"  }",
"",
"  private parseIterationResult(raw: string, iteration: number): IterationResult {",
"    try {",
"      const clean = raw.replace(/```(?:json)?\\n?/g,'').replace(/```/g,'').trim();",
"      const p = JSON.parse(clean);",
"      const result = {python:this.extractCode(p.python||''),summary:(p.summary||'No summary').slice(0,200),enough:Boolean(p.enough),reason:(p.reason||'').slice(0,100)};",
"      console.log('[KIMI:PARSE_OK] iter=' + iteration + ' enough=' + result.enough);",
"      return result;",
"    } catch(e) {",
"      console.error('[KIMI:PARSE_FAIL] iter=' + iteration);",
"      return {python:this.extractCode(raw),summary:'parse fallback',enough:false,reason:'JSON parse failed'};",
"    }",
"  }",
"",
"  private extractCode(text: string): string {",
"    const m = text.match(/```(?:python)?\\n?([\\s\\S]*?)```/);",
"    return m ? m[1].trim() : text.trim();",
"  }",
"}"
];
fs.writeFileSync('src/kimi.ts', lines.join('\n'), 'utf8');
console.log('OK - kimi.ts written');
