const fs = require('fs');
const lines = [
"import OpenAI from 'openai';",
"import { gonkaFetch, resolveAndSelectEndpoint } from 'gonka-openai';",
"",
"export interface IterationResult {",
"  python: string;",
"  summary: string;",
"  enough: boolean;",
"  reason: string;",
"}",
"",
"export class KimiClient {",
"  private gonkaPrivateKey: string;",
"  private model: string;",
"",
"  constructor(gonkaPrivateKey: string) {",
"    this.gonkaPrivateKey = gonkaPrivateKey;",
"    this.model = 'moonshotai/Kimi-K2.6';",
"  }",
"",
"  private async getClient(): Promise<OpenAI> {",
"    const { selected } = await resolveAndSelectEndpoint({ sourceUrl: 'http://node2.gonka.ai:8000' });",
"    const fetch = gonkaFetch({ gonkaPrivateKey: this.gonkaPrivateKey, selectedEndpoint: selected });",
"    return new OpenAI({ apiKey: 'mock-api-key', baseURL: selected.url, fetch });",
"  }",
"",
"  async generateIteration(dataDescription: string, question: string, iterationSummaries: string[], iteration: number, maxIterations: number): Promise<IterationResult> {",
"    const systemPrompt = 'You are a Python data analyst. Each iteration: write focused Python under 25 lines for ONE hypothesis, summarize in 30 words, signal enough=true when done. FORBIDDEN: pandas/numpy/matplotlib. CSV in CSV_DATA. Output: print(json.dumps({\"result\":...})). Return JSON only: {\"python\":\"...\",\"summary\":\"...\",\"enough\":bool,\"reason\":\"...\"}';",
"    const contextBlock = iterationSummaries.length > 0 ? '\\n\\nKnown: ' + iterationSummaries.map((s,i) => (i+1)+': '+s).join('; ') : '';",
"    const userMessage = 'Schema:\\n' + dataDescription + '\\n\\nQuestion: ' + question + ' (iter ' + iteration + '/' + maxIterations + ')' + contextBlock + '\\n\\nOne hypothesis, no repeats.';",
"    console.log('[KIMI:PROMPT] iter=' + iteration + ' summaries=' + iterationSummaries.length);",
"    const t0 = Date.now();",
"    const raw = await this.callAPI(systemPrompt, userMessage, 2000, 'iter'+iteration);",
"    console.log('[KIMI:DONE] iter=' + iteration + ' elapsed=' + (Date.now()-t0) + 'ms');",
"    return this.parseIterationResult(raw, iteration);",
"  }",
"",
"  async generateFinalAnalysis(question: string, summaries: string[], language: string = 'ru'): Promise<string> {",
"    const lang = language === 'ru' ? 'Respond in Russian. Plain text, no markdown.' : 'Respond in English.';",
"    const sys = 'You are a business analyst. ' + lang + ' Give: 1-2 sentence summary, key findings, 1 recommendation.';",
"    const msg = 'Question: ' + question + '\\n\\nFindings:\\n' + summaries.map((s,i) => (i+1)+'. '+s).join('\\n');",
"    return await this.callAPI(sys, msg, 1000, 'final');",
"  }",
"",
"  private async callAPI(systemPrompt: string, userMessage: string, maxTokens: number, label: string): Promise<string> {",
"    try {",
"      const client = await this.getClient();",
"      const response = await client.chat.completions.create({",
"        model: this.model, max_tokens: maxTokens,",
"        messages: [{role:'system',content:systemPrompt},{role:'user',content:userMessage}],",
"        temperature: 0.6,",
"      });",
"      const content = response.choices[0]?.message?.content || '';",
"      console.log('[KIMI:API] label=' + label + ' tokens=' + response.usage?.total_tokens);",
"      return content.trim();",
"    } catch(err) { console.error('[KIMI:ERROR] ' + String(err)); throw err; }",
"  }",
"",
"  private parseIterationResult(raw: string, iteration: number): IterationResult {",
"    try {",
"      const clean = raw.replace(/```(?:json)?\\n?/g,'').replace(/```/g,'').trim();",
"      const p = JSON.parse(clean);",
"      const result = {python:this.extractCode(p.python||''),summary:(p.summary||'No summary').slice(0,200),enough:Boolean(p.enough),reason:(p.reason||'').slice(0,100)};",
"      console.log('[KIMI:PARSE_OK] iter=' + iteration + ' enough=' + result.enough);",
"      return result;",
"    } catch(e) {",
"      console.error('[KIMI:PARSE_FAIL] iter=' + iteration);",
"      return {python:this.extractCode(raw),summary:'parse fallback',enough:false,reason:'JSON parse failed'};",
"    }",
"  }",
"",
"  private extractCode(text: string): string {",
"    const m = text.match(/```(?:python)?\\n?([\\s\\S]*?)```/);",
"    return m ? m[1].trim() : text.trim();",
"  }",
"}"
];
fs.writeFileSync('src/kimi.ts', lines.join('\n'), 'utf8');
console.log('OK - kimi.ts written');
